<?php

declare(strict_types=1);

namespace Glueful\Extensions\Subscriptions\Tests\Integration;

use PHPUnit\Framework\TestCase;

/**
 * Task 12 dependency gate (design spec §2's publication-gate rule): "Each
 * publication gate requires the next phase to remove any temporary
 * sibling-repository override for the dependency being released and prove
 * clean resolution from the published registry." Phase B (subscriptions
 * 2.2.0) removes the `../payvia` path repository this repo carried since
 * payvia 2.4 was a require-dev-only sibling-checkout fixture, and now
 * resolves the published `glueful/payvia` ^2.5 from the real registry.
 *
 * Asserted against `vendor/composer/installed.json` (NOT the checked-in
 * `composer.lock`, which this library package's own `.gitignore` keeps
 * out of version control) -- `installed.json` is regenerated by every
 * `composer install`/`update` and is exactly what actually landed in
 * `vendor/`, so it proves the same thing a lock-file assertion would
 * without requiring an override of the package's own ignore convention.
 */
final class PayviaDependencyTest extends TestCase
{
    /** @return array<string,mixed> */
    private function payviaInstalledPackage(): array
    {
        $installedPath = dirname(__DIR__, 2) . '/vendor/composer/installed.json';
        self::assertFileExists($installedPath);

        $installed = json_decode((string) file_get_contents($installedPath), true, 512, JSON_THROW_ON_ERROR);

        foreach ((array) ($installed['packages'] ?? []) as $package) {
            if (($package['name'] ?? null) === 'glueful/payvia') {
                return $package;
            }
        }

        self::fail('vendor/composer/installed.json has no glueful/payvia package entry.');
    }

    public function testComposerJsonNoLongerDeclaresAPayviaPathRepository(): void
    {
        $composerPath = dirname(__DIR__, 2) . '/composer.json';
        $composer = json_decode((string) file_get_contents($composerPath), true, 512, JSON_THROW_ON_ERROR);

        foreach ((array) ($composer['repositories'] ?? []) as $repository) {
            self::assertNotSame(
                'payvia',
                $repository['name'] ?? null,
                'composer.json must not carry a payvia sibling-repository override once published '
                    . '2.5 is required.'
            );
            if (($repository['url'] ?? null) === '../payvia') {
                self::fail('composer.json still repository-overrides glueful/payvia onto ../payvia.');
            }
        }

        self::assertSame('^2.5', $composer['require-dev']['glueful/payvia'] ?? null);
    }

    /**
     * Belt-and-suspenders against the path override quietly returning: no
     * `repositories` entry of type `path` may mention payvia in its url at all,
     * regardless of name/shape.
     */
    public function testComposerJsonHasNoPathRepositoryMentioningPayviaAnywhere(): void
    {
        $composerPath = dirname(__DIR__, 2) . '/composer.json';
        $composer = json_decode((string) file_get_contents($composerPath), true, 512, JSON_THROW_ON_ERROR);

        foreach ((array) ($composer['repositories'] ?? []) as $repository) {
            if (($repository['type'] ?? null) !== 'path') {
                continue;
            }

            self::assertStringNotContainsStringIgnoringCase(
                'payvia',
                (string) ($repository['url'] ?? ''),
                'a path repository whose url mentions payvia would silently reintroduce the override.'
            );
        }
    }

    public function testInstalledPayviaDistIsPublishedNotAPathOverride(): void
    {
        $package = $this->payviaInstalledPackage();

        self::assertIsString($package['version'] ?? null);
        self::assertStringStartsWith('2.5', (string) $package['version']);

        $distType = $package['dist']['type'] ?? null;
        self::assertNotSame(
            'path',
            $distType,
            'glueful/payvia must resolve from the published registry, not a local path override.'
        );
        self::assertSame('zip', $distType, 'a published Composer package dist is a zip, not a symlinked path.');

        self::assertSame(
            'git',
            $package['source']['type'] ?? null,
            'a published Composer package source is a git checkout of the tagged release.'
        );

        self::assertArrayNotHasKey(
            'options',
            $package['dist'] ?? [],
            'a path-repository dist carries a symlink "options" block; a published dist never does.'
        );
    }

    public function testInstalledPayviaRuntimeMatchesThePublishedVersion(): void
    {
        // Belt-and-braces: the ACTUAL installed package (what vendor/ + autoload
        // resolved this test run against), not just installed.json's manifest.
        $installedComposerPath = dirname(__DIR__, 2) . '/vendor/glueful/payvia/composer.json';
        self::assertFileExists($installedComposerPath);

        $installed = json_decode((string) file_get_contents($installedComposerPath), true, 512, JSON_THROW_ON_ERROR);

        self::assertSame('2.5.0', $installed['version'] ?? null);
    }
}
